### ISSUE TITLE
Missing UI Customization values

### ISSUE THREAD

**Issue by sbo-nemlig** [Nets-mobile-acceptance/Netaxept-Android-SDK#18]
After updating to the news version of the SDK we can see that below values are missing in the SDK.
They are still in your documentation and we use them in our integration 
- tokenCardCVCLayoutBackgroundColor
- toolbarActionButtonTextColor
- toolbarBackgroundColor
- toolbarTitleColor
- buttonBackgroundColor
- bodyBackgroundColor
- validFieldBorderColor
- errorFieldBorderColor
- inputTextHintColor
- fieldTextColor
- fieldBackgroundColor
- labelTextColor
- buttonTextColor

**Comment by Miss-PiA** [comment]
Hello @sbo-nemlig 

Since version 2.0.0 all color attributes are set via PiaSDKTheme. You can check the implementation in sample as 
https://github.com/Nets-mobile-acceptance/Netaxept-Android-SDK/blob/c3cca57c227cbf77f4fb469e04f24f7e1f4a53e7/PiaSample/app/src/main/java/eu/nets/pia/sample/ui/activity/UICustomizationActivity.java#L86

You can also refer the implementation guide in the documentation under section "UI Customization API"
https://github.com/Nets-mobile-acceptance/Netaxept-Android-SDK/blob/master/documentation/START%20-%20Overview%20of%20Netaxept%20Android%20SDK.html.

Best regards

**Comment by sbo-nemlig** [comment]
Thx for the quick reply :)
