### ISSUE TITLE
Purpose of the SDK?

### ISSUE THREAD

**Issue by mortenholmgaard** [Nets-mobile-acceptance/Netaxept-Android-SDK#6]
What is the purpose of this SDK compared to iOS?
It seems like you should implement most of it youself anyway. 

For example this code - Why do we have to implement PaymentFlowCache, PaymentRegisterRequest, PaymentRegisterResponse and MerchantRestClient? This seems to be basic code that should be in the SDK, and not be our responsibility to maintain when every some fields change!

```
class NetsPaymentHandler : RegisterPaymentHandler {
    override fun doRegisterPaymentRequest(saveCard: Boolean): TransactionInfo {
        val paymentFlowCache: PaymentFlowCache = PaymentFlowCache.getInstance()
        val paymentRegisterRequest: PaymentRegisterRequest = paymentFlowCache.getPaymentRegisterRequest()
        paymentRegisterRequest.setStoreCard(saveCard)
        MerchantRestClient.getInstance().registerPayment(paymentRegisterRequest)
        if (!paymentFlowCache.isFinishedWithError()) {
            val paymentRegisterResponse: PaymentRegisterResponse = paymentFlowCache.getPaymentRegisterResponse()
            return TransactionInfo(
                paymentRegisterResponse.getTransactionId(),
                paymentRegisterResponse.getRedirectOK()
            )
        }
        return null
    }
}
```

**Comment by Miss-PiA** [comment]
Hello @mortenholmgaard ,

Appreciate you reaching out to us.

The code that you have mentioned is used to display the various payment methods list. It is upto the merchant/integrator as to how to display the list and what data to display in the list. What we have given is just a sample of how it can be implemented. We are open to suggestions, maybe you can suggest a way which maybe more efficient.

Thank you.

**Comment by mortenholmgaard** [comment]
I just don't get why we should implement the api to this endpoint and others. Why is there not a Service in the SDK to call where all the fields are mapped and wrapped? As I see it there is only a little client specific in the PaymentFlowCache else the rest is in the arguments parsed to the requests.
https://shop.nets.eu/web/partners/register

**Comment by Miss-PiA** [comment]
Hi Morthen,

The sample app is just a reference app to show you how to integrate our SDK. The Restful contract between sample app and sample merchant backend is implemented for demo and reference purpose. You need to implement your own contract to communicate with your backend to trigger each API requests to Netaxept from your backend and our SDK is used to handle the interaction of Card sensitive data entry. So, what SDK is expected is the register function callback handler that SDK could trigger on behalf of your App to you backend to fire a Register call to netaxept. Because, SDk don't have the token which is used to make the Restful request towards Netaxept and should not store your token in the mobile environemnt rather in your backend environment.  You can check the SDK API to feed the corresponding parameters to intialize the payment flow and other rest will be  handled by merchant App.
