### ISSUE TITLE
Error loading request: mobilepayonline-test://online?paymentid=`UUID`

### ISSUE THREAD

**Issue by phoenixria** [Nets-mobile-acceptance/Netaxept-Android-SDK#62]
SDK: 2.6.3, 2.6.4

Sandbox App: 5.20.0

Steps to reproduce:
1. Register a payment on the server and get the transaction id.
2. Call 'callbackWithWalletURL.successWithWalletURL(uri)'
3. Get an error.

Error: Error loading request: mobilepayonline-test://online?paymentid=b00624d7-802b-420f-83cc-ef8a310c875e
Inside data object - "net::ERR_UNKNOWN_URL_SCHEME"
See the screenshot for details.

![Screenshot_20220826_175428](https://user-images.githubusercontent.com/752172/186933284-e471cc1f-7796-461c-8a08-2b8fb23a09e5.png)

On live everything works, only sandbox produces this error. Also, about a month ago, when it was last checked, everything was working fine. The codebase related to Netacept payments didn't change on the mobile and backend sides. Just stopped working with this error. Visually, seems like SDK starts activity, some progress is performed and then a user returns to the app and sees the error from the SDK.

If you need details, please ask me.

Best regards,
Ihor

**Comment by lilemma** [comment]
We are experiencing the same problem.

![Screenshot 2022-09-29 at 08 48 59](https://user-images.githubusercontent.com/36534776/192959513-a1fec457-a7a8-46f9-8a2e-38bce871e5ff.png)

This issue has been around for a month now, with no details on when it will be fixed @Miss-PiA ? 
Please respect that we need another answer than the standard "it will be fixed in the next release.", It is critical that we are able to test payments in sandbox.

**Comment by Miss-PiA** [comment]
Hi @phoenixria , @lilemma ,

Thank you for finding this issue for us.

After investigation, the MobilePay universal link is not working for our SDK. So we have to add new `mobilepayonline-test` scheme support to the app switch logic.

You will receive this feature change in our next release.

**Comment by Miss-PiA** [comment]
Hi,
Issue has been fixed in Netaxept-Android-SDK v2.7.0.
Thanks
